### ISSUE TITLE
where are the missing devs

### ISSUE THREAD

**Issue by masterslavedb** [ayojs/ayo#119]
When are all the URMs going to come out of the woodwork and make this project great again? It's been 2 months and I thought that was the entire premise of the fork?

**Comment by aredridel** [comment]
@ayojs/moderation

**Comment by aredridel** [comment]
@ayojs/moderation

**Comment by masterslavedb** [comment]
Just an honest question, not trying to offend.

**Comment by zkat** [comment]
@masterslavedb I'm gonna close and lock this thread: the "premise of this fork" has multiple issues already dedicated to it on this issue tracker, and you should refer to those for discussions about this stuff. I'd also ask that you consider whether you really expect people to believe you're engaging in good faith when you have a username like yours, and you open your issue with something that's more provocative than useful (again, because we've had this discussion before).

Cheers!
