### ISSUE TITLE
COC violates Code of Conduct

### ISSUE THREAD

**Issue by huntertrevor** [ayojs/ayo#130]
The code of conduct violates the code of conduct. Per the code of conduct, this is not appropriate; please edit it.

Namely, the example re: Nazis [here](https://github.com/ayojs/ayo/blob/latest/CODE_OF_CONDUCT.md#the-nope-case) is extremely unwelcoming and exclusive language, and is disrespectful of differing political viewpoints and fashions.

There must be a better way to illustrate these examples than to directly attack an ideology or group of people.

**Comment by stefee** [comment]
The Nope Case is included as a specific exception to ensure that Nazis are not welcome, included or respected with regards to the usual moderation process.

I can assure you: this is absolutely intentional.

@huntertrevor I'm taking your complaint as a clear attempt at presenting a "reverse-ism" and am going to close and lock this thread as this violates our CoC. Please consider this a warning.
