### ISSUE TITLE
Any logo ideas?

### ISSUE THREAD

**Issue by evanlucas** [ayojs/ayo#17]
Any ideas on the logo?

**Comment by hypesystem** [comment]
It would be cool to play on the shapes (hexagons) of the Node logo, but make them softer/more human?

**Comment by junosuarez** [comment]
Just for fun and reference, here's the old iojs logo thread from back in the day. Enjoy! https://github.com/nodejs/node/issues/37

**Comment by ohcrfpv** [comment]
my idea,lol,coarse,not finished ![logo](https://user-images.githubusercontent.com/3256161/29697997-0834b660-8985-11e7-8a48-26daaf3779f5.png)

**Comment by denistsoi** [comment]
spent 15 minutes with hexagons and just realised - ... 
using "fork" images would actually make more sense...

**Comment by denistsoi** [comment]
![ayo](https://user-images.githubusercontent.com/3061779/29698565-fa19452e-8988-11e7-8451-12b7ce78968d.png)

Explanation:
think hexagons are somewhat overdone - somewhat also cliché
experimenting with an octagon.

The dot in Y - could represent the individual without being explicit as an "I" - and acts as a visual reminder that the individual within the community is as important as a conduit for community and progression. (you need to act in accordance with the community around you).

I opted for a 'retro' font type (Google font `Audiowide`) look as it's reminiscent of the 80's optimism and rebellious nature within tech that was so prominent in that era) - I didn't go for a courier new typeface since it's a bit old school (and the schools of thought from that era are quite stifling and non-welcoming, "dogmatic").

I could play with colors but wanted to through this out there to view

**Comment by Fishrock123** [comment]
ah yes but, hexagons fit oh so nicely into that sticker spec everyone loves ;D

**Comment by denistsoi** [comment]
ahhh! - nice I didn't even think about that!

I'll play around with hexagons :D




On Fri, Aug 25, 2017 at 1:38 PM, Jeremiah Senkpiel <notifications@github.com

**Comment by varjmes** [comment]
@fewspider I love it

**Comment by ohcrfpv** [comment]
@varjmes 😛

**Comment by bali182** [comment]
How about this?
![photo](https://user-images.githubusercontent.com/3879181/29705999-38877bb6-8978-11e7-86d9-5203f9d86806.jpg)

**Comment by denistsoi** [comment]
Orange backdrop
![ayo-orange](https://user-images.githubusercontent.com/3061779/29710018-395c40c8-89c1-11e7-8d22-ae5894d4661b.png)

Blue Backdrop
![ayo-blue](https://user-images.githubusercontent.com/3061779/29710017-392fb300-89c1-11e7-819a-2f48c736576c.png)

**Comment by yetzt** [comment]
geometries (2d and 3d), colors with a meaning and has an A a Y and a (hexagonal) O. 
![ayo](https://user-images.githubusercontent.com/152031/29711836-6106d006-8986-11e7-876d-3559240f48b3.png)
(just a quick draft)
(can be "seen" as a cube with a half in the back and a sixteenth-corner in the front missing)

**Comment by Mathspy** [comment]
I think that the logo should be a way to represent why Ayo exists in first place so something with a [human](https://i.pinimg.com/736x/20/78/3f/20783fe4d53ad8d10e4a6d4aeede17f7--logo-s-logo-ideas.jpg) or [two](https://stocklogos-pd.s3.amazonaws.com/styles/logo-medium-alt/logos/image/1358956442-22a015a350695df683dc8067b163f249.png?itok=_kPZOoZ-)

Some ideas:
- Two humans holding the old Node logo (or a slightly modified version of it) together
- The Node logo used as the face of a human (the human should also be in a welcoming pose)

Also note how my proposal could actually be "merged" with any of the previous proposals in form of replacing the Node logo in one of the above with whichever everyone seems to lean towards the most

**Comment by steward379** [comment]
I am a designer and junior developer. It's a great chance to make ayo.js a little cooler, with some neon elements...
![ayo-01](https://user-images.githubusercontent.com/10606663/29723667-0eaff82e-89f8-11e7-9e4b-6083bda65cc5.png)

**Comment by Qard** [comment]
@yetzt That's really cool! I like all the colors and the layered transparency. It really matches what ayo is all about, in my opinion. 😸

**Comment by hybrisCole** [comment]
how about a snowflake?

**Comment by zkat** [comment]
My submission:

![ayo](https://s-media-cache-ak0.pinimg.com/564x/63/a6/a9/63a6a9296b01b2979e27d1f2be42c962.jpg)

**Comment by stefansedich** [comment]
I feel this submission is close to the original but somewhat subtly different at the same time.

![ayo](http://i.imgur.com/hYzlX1v.png)

**Comment by tenthirtyone** [comment]
_[Edit by @zkat: if you're not willing to engage in a well-intentioned manner, please refrain from doing so. There are better ways to have a conversation with the project than this. Yes, I'm going to be more aggressive with moderation until the initial burst of trolls stops creeping in -- we'll have more formal, established processes as we start documenting them.]_

<details>
![image](https://user-images.githubusercontent.com/6285466/29735994-4822279e-89cb-11e7-94d3-93b512a69ba2.png)
</details>

**Comment by djangoconcardiff** [comment]
_[Edited by @zkat: I am incredibly suspicious of a brand-new, seemingly throwaway account making a proposal as racially and violently charged as this one. I am moderating it behind a cut, even though I'm leaning towards removal. If you want to engage with the project, please try and do so in a well-intentioned way -- you'll have to work a bit hard to convince me that this one was well-intentioned in context.]_

<details>
One of my favorite characters from the TV show 'The Wire' was a homosexual African-American man named Omar Little. Right before he would rob the drug dealers (thus performing a sort of restorative justice role in his society), he would yell... "Ay yo!"

![9b8b118ce625c585866078238093062f--the-wire-gangster-movies](https://user-images.githubusercontent.com/31296790/29736594-c304202a-89d0-11e7-90ca-4bf3854573f4.jpg)

I can't think of a better symbol for our project.
</details>

**Comment by darling** [comment]
I am traveling but will come back with a few ideas I have Monday that you guys might love.

**Comment by jacktuck** [comment]
<img src='https://media.tenor.com/images/e1ac72dcbc7540e357b6fc57edf1ce79/tenor.gif'>

**Comment by stranger26** [comment]
Just a thought, maybe something like o//o?
So it forms some what like ayo yet can see some resemblance of i/o.
Am not a designer, just throwing the idea out. Will be super cool if it turns out to be ambigram too. 😃

**Comment by nejento** [comment]
What if the logo was representing mainly the code. With the idea of that main green color, eventhough there isn't a lot of hexagons, they can be easily imagined…

Black on transparent (or white, lol 😛)
![ayosmall](https://user-images.githubusercontent.com/1355003/29746005-baf45ee4-8acb-11e7-9c70-7a2cebb80956.png)
![ayojssmall](https://user-images.githubusercontent.com/1355003/29746004-b63864ae-8acb-11e7-9b21-3a0c947ae405.png)

White on black:
![ayowhitesmall](https://user-images.githubusercontent.com/1355003/29746001-a9d2bb10-8acb-11e7-95b3-784b4835d5e1.png)

You could then do something like this:
![ayowikismall](https://user-images.githubusercontent.com/1355003/29746002-aef09680-8acb-11e7-91cc-b69d4a7bf09a.png)

Multiple color variations are possible just by changing the <> color:
![ayojssmallcolorvariation](https://user-images.githubusercontent.com/1355003/29746306-ce765fda-8ad5-11e7-9833-1fa517dbcdc8.png)

**Comment by zkat** [comment]
Y'all doing all this neon, and I feel like I need eclipse sunglasses just to look at my screen. lol

**Comment by darling** [comment]
@zcat Yeah. I get home tmrw, planning to pop our illustrator and get a few vectors and graphics out.

**Comment by Mosoc** [comment]
![ayojs-box](https://user-images.githubusercontent.com/11909428/29749020-b5f87780-8b5d-11e7-82e3-f59c4d2d195b.png)

![ayojs-race](https://user-images.githubusercontent.com/11909428/29749060-dc179d5a-8b5e-11e7-82a4-ced608dcb21f.png)

**Comment by 1kasper** [comment]
How about something like this:
![MEGALOGO](https://raw.githubusercontent.com/ApplePride/PIDOR/master/visualScheme.jpg)

**Comment by Fybis** [comment]
![img_20170827_113959](https://user-images.githubusercontent.com/22520943/29752485-347a666c-8b5f-11e7-9ddd-2535caae193b.jpg)

**Comment by gh67uyyghj** [comment]
Great project name, that's how I will remember it
![fireshot capture 6 - aye-nobody-gives-a-fuck jpeg 418x715 _ - http___weknowmemes com_wp-content_u](https://user-images.githubusercontent.com/13534639/29754598-368922e0-8b91-11e7-9978-fcbcaf102794.png)

**Comment by 1kasper** [comment]
Stop anal moderation, please.

How about something like this?
![ayo js](https://user-images.githubusercontent.com/14055243/29757282-e8bc319e-8bd4-11e7-8e92-15897496f8cd.jpg)

**Comment by JMV2112** [comment]
![1503895911962](https://user-images.githubusercontent.com/1395419/29759786-2ccf8a58-8b84-11e7-8eed-5959a91f515f.png)

**Comment by darling** [comment]
![umlogo](https://user-images.githubusercontent.com/29882716/29768287-86ed1f62-8b9a-11e7-9983-9ddbd7a6bf68.png)

Logos by themselves,

![black-asset 2](https://user-images.githubusercontent.com/29882716/29768309-9dbf3dba-8b9a-11e7-9922-f68a54443fd1.png)
(White logo, I use a black GitHub theme, so.)
![white-logo](https://user-images.githubusercontent.com/29882716/29768310-9ee51840-8b9a-11e7-91ac-8773b9716333.png)


The thought behind such a simple logo, is not only is it cool to brand with lines, and we have an icon to use, but it's really simple and professional. We don't have to enforce a color scheme to make the logo work unless it's needed by the design. 

It's a very "lightweight" (the line's weight is very small) and "fast" (the logo is simple and really easy to remember)

It's ever so noticeable, but the logo is slanted, just barely. I should fix that. I was just messing around with another concept, found this, and noticed when it was too late (just now).

But I want to see someone come up with something or mine to get picked. 

I also have source files for everyone to use if picked, lmk.

One more thing, the logo with its header:
https://gist.github.com/adorable/c9ffbc0a1a8e4283711e974c1f83c74c

lmk.

**Comment by Angelmmiguel** [comment]
Hello all,

Based on the hexagon suggestion, I've created a logo around this shape. I tried to follow a similar node's logo style, but I kept shapes more open, like the purpose of this fork. It uses a lighter green with two tones, to create an small contrast between the different elements in the logo.

Every letter includes an small hexagon in the middle. I wanted to show every letter as an eye to show the important human factor of this project. In addition, every letter is based on the same shape (we all work in the same direction) but is different from the other one (trying to show diversity).

Also, I know it's important to have a small and "squared" version of the logo for stickers, favicons, etc. I created that variation, but I need to continue working on it because I think it doesn't look well in small sizes.

So, this is my proposition for the logo:

![Ayo.js logo proposition. The three shapes are based on an hexagon with slightly differences between them to show diversity and complete the shape of the letters. The base color is a light green called Tradewind](https://user-images.githubusercontent.com/4056725/29770779-d8a68a0e-8bf0-11e7-9ee6-ca7476a91a27.png)

If you have any suggestion or something you want to improve, just ping me here 😄

PS: I like the "opacity effect" with black backgrounds.

**Comment by darling** [comment]
@Angelmmiguel It bugs me with the dark background for some reason.

**Comment by Angelmmiguel** [comment]
I'm gonna check it. Anyway, I can send you the source code if you want to change it :). Could you send me your email?

**Comment by shadowcodex** [comment]
I'm wanting to see one where the "Y" is the fork icon ...

**Comment by fuggg** [comment]
My initial idea was to make the "O" a hexagon, and workaround putting "AY" inside/around it. As I don't like mixing different fonts and styles in logo, I tried cutting parts of that hexagon to form other letters, and this is what I came up with.
![jfsddw](https://user-images.githubusercontent.com/31390188/29791214-7ae2c9cc-8c3c-11e7-8099-afc38f719e50.png)
This can be made into more compact version, which I think would make a badass sticker :smiley: 
![quozxn](https://user-images.githubusercontent.com/31390188/29791242-8c9113e0-8c3c-11e7-986a-bc841ea161e7.png)
PS: I'm pretty bad at this (made it with GIMP), so if someone wants to improve it, feel free

**Comment by stefee** [comment]
I'm not a huge fan of geometric type. It also perhaps doesn't best convey the human emphasis of the project.

'Ayo' looks pretty good in lowercase [Arimo](https://fonts.google.com/specimen/Arimo). Gist with examples [here](https://gist.github.com/srilq/c7b742a5a99e82ebe460e73916b44fc9). (I didn't think too much about the colour in the example here, that's a whole other decision).

![ayo](https://gist.githubusercontent.com/srilq/c7b742a5a99e82ebe460e73916b44fc9/raw/9855edccdf03d8d40361a01fa8afae3b4e671c15/ayo.png)

This is just a very basic wordmark. If the preference is to have something more distinctive, then this is not appropriate, but I would argue that the benefit of simplicity outweighs the need for a particularly recognisable brand. I think a good colour choice alone would make this distinctive enough.

I like the basic cube or hexagon outline or fill (with sharp corners) for a symbol.

**Comment by refack** [comment]
***Not trolling*** (just a bit tongue in cheek). Maybe incorporate one of the following, as a wink at the motivation behind the fork.

![image](https://user-images.githubusercontent.com/96947/29842319-7f30311e-8cd6-11e7-8b59-397c8dcee474.png)

(It was not my idea to use bunnies to represent "cruelty free")
![image](https://user-images.githubusercontent.com/96947/29842393-b985e192-8cd6-11e7-9802-0f02ff6dde55.png)

**Comment by gwigz** [comment]
"IO", [really?](
https://youtu.be/zKCrSN9oXgQ?t=71)

**Comment by frazras** [comment]
Modification of @adorable 's idea. Feel free to imagine it with color.
![ayo](https://user-images.githubusercontent.com/177070/30008890-9384b47c-90f1-11e7-93b5-6047ac3a9e77.png)

**Comment by scotttrinh** [comment]
I'm not a designer, but what about a logo that incorporates two people shaking hands or some other (more multicultural?) nod to cooperation and people?

**Comment by OKNoah** [comment]
Really low effort, but the bunny's ears are the Y or something?

![ayojs](https://user-images.githubusercontent.com/3739277/30159228-c2bc6a90-937c-11e7-9af4-e7b07dbe0969.png)

**Comment by OKNoah** [comment]
Another lazy proof of concept. I think it's compass.

![ajojs_compass](https://user-images.githubusercontent.com/3739277/30193831-71679600-9404-11e7-8049-1fd96028bfca.gif)

And some ideas about referencing the pronunciation confusion:

![ayojs_iojs](https://user-images.githubusercontent.com/3739277/30194013-8ed29f18-9405-11e7-9c30-ca174efaf9b2.png)

![ayjs_io_dot_js](https://user-images.githubusercontent.com/3739277/30194022-987bbae0-9405-11e7-9ede-0a0844982bc3.png)

**Comment by OKNoah** [comment]
¯\\_(ツ)_/¯ 

![ayojs_anarchy_flags-js](https://user-images.githubusercontent.com/3739277/30194545-c06a9adc-9408-11e7-888a-0830fe4e0547.png)

**Comment by liquidnuker** [comment]
Hello all. Just sharing my idea.

![ayo](https://user-images.githubusercontent.com/19706437/31082618-55125f0a-a744-11e7-9c46-4329629284eb.jpg)

The font used is lato:
https://www.fontsquirrel.com/license/lato

**Comment by OKNoah** [comment]
There is a user giving away some free logos. Here are some that have little interest from others and might go along with the project.

https://github.com/arasatasaygin/openlogos/issues/4
https://github.com/arasatasaygin/openlogos/issues/13
https://github.com/arasatasaygin/openlogos/issues/19
https://github.com/arasatasaygin/openlogos/issues/23

**Comment by nukeop** [comment]
It's dead, Jim.

**Comment by OKNoah** [comment]
@nukeop were the issues resolved?

**Comment by benjamingr** [comment]
@OKNoah well, I can't speak for Ayo but at least one big initiative (threading and worker_threads) that was developed mostly here ended up landing in Node.js

**Comment by jacktuck** [comment]
<img src="https://media1.giphy.com/media/d5Fbtoj47ROk0J9IgW/200.gif?cid=da7f08c75b2a4db56b49314763b599f6"/>

**Comment by bali182** [comment]
Guys, it has been a while, I think we have a winner!
https://github.com/ayojs/ayo/issues/17#issuecomment-324857237

**Comment by OKNoah** [comment]
@bali182 It's property of [Shutterstock](https://www.shutterstock.com/image-illustration/3d-render-alien-head-12331420). So it would need to be licensed from them.

**Comment by tenthirtyone** [comment]
Is this tantrum still being thrown?

**Comment by OKNoah** [comment]
@techjeffharris What tantrum?

**Comment by nukeop** [comment]
After a bunch of documentation updates by non-programmers, it looks like they realized the futility of it and left.

**Comment by benjamingr** [comment]
I think the amount of disrespect people have here to developers who are writing the tools they are using is astounding.

Also, the lack of empathy people have towards others building software is confusing. If some people went to build things on another repo why is that offensive to you? Attacking people on a repo trying to do something feels _very_ insecure. Ayo is not and was not an attack on Node.js, Deno is not and was not an attack on Node.js, any future forks and new idea explorations aren't attacks on Node.js.

This is crystal clear to the people _working_ on Node.js - we don't see these things as attacks, we don't see them as negative and we don't see them as something to try to end. Experimentation is great and people doing things differently is great. Let's __encourage__ people to try different approaches and solutions rather than attack them. Node.js is successful because it is/was innovative - let's _encourage_ innovation and challenging our ideas rather than shut it down.

@nukeop @tenthirtyone @bali182 - I ask you to reconsider your comments here. I realize you're probably doing this to try and help Node.js from some idea of "having it unified" as a goal. You are attacking people and encouraging fewer experimentation and more burnout. 

Also, I assume you won't be using any of the APIs these "non-programmers" wrote that got merged back into Node.js then.

------

@evanlucas I ask that you consider locking this issue as it deteriorated into attacks. While I am not (and was not) an Ayo member - the fact people are showing up just to attack people for trying to build stuff seems overly aggressive to me.

**Comment by u1f408** [comment]
@ayojs/moderation can this thread be locked?

**Comment by OKNoah** [comment]
@0x52a1 Is it possible to ban trolls rather than lock?

**Comment by nukeop** [comment]
You're reading way too much into a couple of lighthearted jokes over a dead project

nothing more insecure than demanding locking and banning every time anyone says something you don't like

**Comment by OKNoah** [comment]
@nukeop Can I find it a bit ironic that folks are being chastised for "reading too much into" something on a website where source code is shared so that we can read deeply into it? If you aren't taking your own behaviour here seriously, why not just leave altogether? I use plenty of software that hasn't been updated in months or years, but I don't see you stalking the comments making "lighthearted jokes" on each of them.

**Comment by nukeop** [comment]
lol ok

**Comment by varjmes** [comment]
Hey, we achieved what we wanted.
Please find somewhere else to chat! :)

FYI this was started by programmers, I'm a self taught programmer of over 4 years, working for Conde Nast. Cheers!
