### ISSUE TITLE
Pluggable JavaScript engine with ABI stable ayo?

### ISSUE THREAD

**Issue by brody2consult** [ayojs/ayo#51]
* ~~**Version**:~~
* ~~**Platform**:~~
* ~~**Subsystem**:~~

ABI stable ayo based on <https://github.com/nodejs/abi-stable-node>. Existing Node 8 API described at <https://nodejs.org/api/n-api.html>.

This plus #50 (move non-essential C++ modules into addons) should enable this project to support iOS.

This + #50 + #40 (worker implementation) could be good enough to supersede the functionality offered by JXCore (<https://github.com/jxcore/jxcore>).

**Comment by Fishrock123** [comment]
Full plugability would likely require an "under-node" JS API layer. The API WG from node has a lot of historical discussions on this worth taking a look at.

**Comment by brody2consult** [comment]
> The API WG from node has a lot of historical discussions on this worth taking a look at.

Do you mean <https://github.com/nodejs/api>? Any other resources worth a look?

**Comment by addaleax** [comment]
I think Ayo is going to support N-API in the same way Node supports it, simply because that makes sense.

Fwiw: I think it would be totally doable to break a few pieces off Ayo into addons that can either be built into the executable or as external addons, but I feel like most people would still want a full-featured build of Ayo to be available by default.
