### ISSUE TITLE
Rename the master branch

### ISSUE THREAD

**Issue by allytwo** [ayojs/ayo#57]
I find the name of the `master` branch offensive. In many parts of the world the word `master` has racial meaning, especially in North America where relatively recently slavery was a thing. I propose to change it to a more welcoming and inclusive word. Maybe `trunk`?

**Comment by zkat** [comment]
All npm repos where I've been able to help it use `latest` as the core branch. Anyone opposed to this rename?

**Comment by codetheorist** [comment]
+1 for latest. 

If it was 'trunk' could that not be associated with racism, with slaves regularly being tied to tree 'trunks' and beaten? I don't think 'trunk' is a good name at all @allytwo

**Comment by zkat** [comment]
After consulting with folks in Discord and checking in with devs, I've made the change. `latest` is the default branch now, and `master` has been deleted. Thanks for the suggestion and contribution!

Because of the nature of stuff like this and because the internet gonna internet, I'm going to preemptively lock this conversation, too. Surely you understand.
