### ISSUE TITLE
Update references to default branch to `latest`

### ISSUE THREAD

**Issue by countnoobula** [ayojs/ayo#64]
Hey everyone! 

As per issue #57 Can an administrator please edit issues to update references to the old default branch to say `latest` instead?

I don't feel we're promoting a safe space with references to such an offensive word in our in history (such as issues #44, #16, etc)

_[Edited by @zkat: removed references to word on OP's request]_

**Comment by zkat** [comment]
I consider this a non-issue, since going forward this won't be part of how we refer to the default branch on this repo anymore. I'm not gonna go edit every single instance in the past, since I don't think the core issue here is whether that word exists or not. If anyone reading this was involved in these issues and feels like making the gesture to edit their past posts, I encourage doing this, since at this point it might be confusing for folks reading why we're referring to an old branch that doesn't exist.

In the meantime, I did take the liberty to edit your issue title and post, since I understand it to have been essentially a request to have that edit be done.

As per #57, because of the nature of the thing, and because it clearly attracts derailers and trolls, I'm going to lock this when I close this. Cheers!
