### ISSUE TITLE
Disconnect between stated values and community behavior

### ISSUE THREAD

**Issue by DelanoJ84** [ayojs/ayo#76]
The disconnect between [the stated reasons for the Ayo fork](https://github.com/ayojs/ayo/issues/36#issuecomment-326598661) and [multiple CoC-breaking statements made by contributing members which are tolerated or ignored](https://github.com/nodejs/TSC/issues/325#issue-253509966) is a topic which will need to be addressed by the Ayo community at some point.

Edited out content after warning by @scotttrinh.

**Comment by zkat** [comment]
Hi, @DelanoJ84!

I believe I'm pretty much the person you're referencing when it comes to this, so I want to say a few things:

1. We do have @ayojs/moderation now, and I am part of that group. I'm also [required to recuse myself](https://github.com/ayojs/ayo/blob/latest/CODE_OF_CONDUCT.md#who-watches-the-watchers) from any enforcement decisions on this, since it has to do with me. This is in their hands and I trust the team to do their work fairly and respectfully for all involved.

2. I was the author of our new [Code of Conduct](https://github.com/ayojs/ayo/blob/latest/CODE_OF_CONDUCT.md), which went through the standard [RFC Process](https://github.com/ayojs/ayo/blob/latest/RFC_PROCESS.md), and was approved as of #69, by a good chunk of folks in this community. I am 100% willing to follow that process because I authored the system that I would like to go through whenever someone would find me in violation of the CoC. I believe it to be just and that it promotes the healthy growth of our community.

So, as part of that process, _as a community member_: I'm sorry about the severity of the words I put out on Twitter. At this point, I don't feel great about saying that because even though I was very angry, I realized that they swept up a number of folks who didn't know the context right away and thus thought it was targeted at them. It was not. But I still did not take enough precautions to make that the case. I don't feel like it would be particularly helpful at this point to delete them, though, and my impression is that the folks hurt would see that as me trying to hide what I did. So, I'll leave it up barring explicit requests to do so. And even if I removed it, I'd like to document their removal.

If you see things like that continue, you are of course totally justified in bringing it up again. I don't assume anyone to be perfect, much less myself. But I think growing is a generally healthy thing to do.

Now, allow me to add a bit of context that was omitted in the original post. Those posts? I was angry because I was reacting directly to a wave of repeated harassment coming from _multiple communities_ in Reddit. And I don't mean "boohoo they said they didn't like me". I mean that I woke up multiple days with an inbox filled with dozens of very angry, anonymous messages with incredibly colorful slurs. Although some of them were a bit repetitive. One of my colleagues, Ashley, dealt with much worse, for much longer, and that added to my frustration. I'm not sure what reaction you expect from someone targeted in that matter, who's seeing their friends also being targeted this way, but this is the one I went with when I had the usual adrenaline rush in my veins. Those messages did not come from a void. Pretending that is so would be, perhaps, _disingenuous_.

I have never, and never will, condone such attacks against anyone that I've disagreed with. And, frankly, I've never taken to anonymous, throwaway accounts when saying what I've said. I think it's important to own my words, even when they get me in trouble of piss people off. Even when they hurt people I care about (well, _especially_ in that case). I imagine you have your own fears here if you're popping up in multiple repositories involving me. I see you already made posts somewhat related to this on the nodejs/TSC repo, even though I'm not a member of that project as of a year ago. I have to admit that there's an undeniable level of intimidation involved by being repeatedly targeted by anonymous accounts, specially when I've had several of these attempting to target my very livelihood over this.

That's all I've got to say. I believe this is appropriate according to our CoC. Let me know if there's anything else I could say that would make you feel more comfortable in a community such as this, if you were to be interested in participating in it in earnest. It continues to be my commitment to build communities that can welcome everyone and create an environment where people can focus on their work, and not on what the people they're working with will do to them.

Cheers~

**Comment by scotttrinh** [comment]
@DelanoJ84 

As @Sequoia pointed out in #67, you are free to distrust and not associate with Ayo.js if you think we are untrustworthy in your estimation, but personal attacks against members of our community is not something we're going to tolerate here, and it's easy to see this message (and the others like it in node's issue tracker) as violating several of the examples of unacceptable behavior outined in our [Code of Conduct](https://github.com/ayojs/ayo/blob/latest/CODE_OF_CONDUCT.md). Please consider this a warning, and if you have a genuine interest in Ayo.js and it's values and goals, both technical and communal, you are welcome to find ways to contribute positively.

For reference our new Code of Conduct has an explicit [enforcement policy](https://github.com/ayojs/ayo/blob/latest/CODE_OF_CONDUCT.md#further-moderation).

**Comment by DelanoJ84** [comment]
@zkat Thank you for taking the time to provide some context. Nobody is helped when someone closes an issue with an unfounded personal attack like "this person is engaging in deliberate, targeted trolling". I will also note that while I commend you willingness to stand behind what you say, these attacks on your livelihood are neither targeted at nor initiated by people with any specific spectrum of opinions. There are legitimate reasons to raise these concerns on a project anonymously.

I'll add that my issue is not with you or even individual specifically but rather the inconsistent and what appears to be biased enforcement of the Code of Conduct. I suspect some of the issues opened which referenced your statements could also be more along the lines of "will you enforce the code of conduct fairly".

**Comment by zkat** [comment]
@DelanoJ84 we did not have an official Code of Conduct until earlier today, and I am not at all involved with Node.js and I'm not responsible for the policies they enact and their own enforcement.

Do you feel like our Code of Conduct is being enforced inconsistently/unfairly here?

**Comment by zkat** [comment]
more context: during the initial weeks of the forks, we got a lot of aggressive messages from strangers, as a community that did not yet have well-established standards. If you think that the closures of issues at that time were unfair and did not go through proper processes, I agree: but I also believe they were the right thing to do until this community had the time to actually get organized and establish a process. This is part of the bootstrapping process. You simply have to do things arbitrarily and based on your best judgment when faced with extraordinary situations before you're able to actually talk about and think through what the right thing to do is.

and it's also very hard to do things fairly when there's been no explicit communication about what "fairness" people are agreeing to prior to engaging. But again, it can't be helped when you haven't had the time to get things together yet.

**Comment by scotttrinh** [comment]
@DelanoJ84 Thanks for the quick acting in editing your comment. I feel like it shows a willingness to work constructively towards addressing your concerns, and thanks @zkat for your genuine and candid responses. 👍

@DelanoJ84 the specific question of "The disconnect between the stated reasons for the Ayo fork and multiple CoC-breaking statements made by contributing members which are tolerated or ignored" seems to be answered rather directly by @zkat in that they are not a member of Node, but please let us know if you feel like they or any of us have not lived up to the expectations we've set out in the Ayo.js Code of Conduct. Since we have an enforcement policy we should be able to address that in a straight-forward manner.

**Comment by janl** [comment]
Given the [CoC incident process outline](https://github.com/ayojs/ayo/blob/latest/CODE_OF_CONDUCT.md#when-something-happens) and [@zkat’s supplied context](https://github.com/ayojs/ayo/issues/76#issuecomment-331030659), I’m satisfied as a moderation team member that this issue is sufficiently addressed. Thanks all. ✌️
